#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.3.5.1 on Thu Apr 21 12:10:56 2005

# Papagayo, a lip-sync tool for use with Lost Marble's Moho
# Copyright (C) 2005 Mike Clifton
# Contact information at http://www.lostmarble.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import os
import wx
import wx.html
import webbrowser
from utilities import *
# begin wxGlade: dependencies
# end wxGlade

class MyHtmlWindow(wx.html.HtmlWindow):
	def __init__(self, *args, **kwds):
		wx.html.HtmlWindow.__init__(self, *args, **kwds)

	def OnLinkClicked(self, linkinfo):
		if linkinfo.GetHref().startswith("http:"):
			webbrowser.open(linkinfo.GetHref())
		else:
			self.base_OnLinkClicked(linkinfo)

class AboutBox(wx.Dialog):
	def __init__(self, *args, **kwds):
		# begin wxGlade: AboutBox.__init__
		kwds["style"] = wx.DEFAULT_DIALOG_STYLE
		wx.Dialog.__init__(self, *args, **kwds)
		self.htmlView = MyHtmlWindow(self, -1, style = wx.SUNKEN_BORDER)
		self.button_12 = wx.Button(self, wx.ID_OK, "OK")

		self.__set_properties()
		self.__do_layout()
		# end wxGlade
		
		self.htmlView.LoadPage(os.path.join(get_main_dir(), "rsrc/about.html"))

	def __set_properties(self):
		# begin wxGlade: AboutBox.__set_properties
		self.SetTitle("About Papagayo")
		self.htmlView.SetMinSize((400, 350))
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: AboutBox.__do_layout
		sizer_13 = wx.BoxSizer(wx.VERTICAL)
		sizer_13.Add(self.htmlView, 0, wx.ALL|wx.EXPAND, 8)
		sizer_13.Add(self.button_12, 0, wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL|wx.FIXED_MINSIZE, 8)
		self.SetSizer(sizer_13)
		sizer_13.Fit(self)
		self.Layout()
		self.Centre()
		# end wxGlade

# end of class AboutBox


